sudo: required

language: ruby

services:
  - docker

# branch whitelist
branches:
  only:
    - master
    - /^stable\/*$/   # stable/

before_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $REGISTRY

script:
  - docker build -t $DOCKER_REGISTRY/$IMAGE:$TAG

after_script:
  # push to docker repo

notifications:
  slack:
    secure: F0jfBAhE1G4IypRxnIQWsF5Ai/XaULtaznZQeIgpA+GKgS03EXh20oOw3Bq2xSTrf6XOtJyZiVbzka9AB8cHkvxXCeC3ehDpKEp0+324Neg4oIHlCcYuGWU179GPFcdvAhHkzHsc6uEkVsx0mg1QMDlzGGCzl9kKEP0kvKXm+GgGbP1J8rFZaRd/fcjo76/9Kbn19yNiIEmFKK1ZbVoJQH0hhIudXzkZY39mbJJHGyc7Zed4ItTljdv17i3n4V7r9iJxd274arRRUDwwAJKsCn0Z66/pMBJ1ShHBpohKyNbd4w6knwpcr6y3ikSx2CmKaZUDKrRqGqbl5NNBZ46XZuGTYAPyLetCwnYNp/iY6D0ID8sWZKQTDHneqI8DNKStH06t6ql58qg81m7qPwxpT+NtW9bObqkcpryE8S4vcauQrTkMsR0TItwKj9iRatymjaEfQpNilkhwiwX8r31stXouqRVKuJ4MFKua4gZa5ePNh7bUuXlYITTNfX4eS7SXFGOKAJ49r3AURad6l2ynAMBcCpch4GkfHOXYS1G/nTC9s1BypaZobw4QmSqTNx9aLS/fburM4+zfc/+FyvbS7xXG7x/8YYg/+ruGpZBnzNFADKKZnQ5Q2vsHqsQObG1VvL7691ofWFwYae7zplBolVgr2RGpJNe8r894ujkn0OU=
    on_success: always # default: always [always|never|change]
    on_failure: always # default: always [always|never|change]
    on_start:   always # default: always [always|never|change]
